server:
  port: 9004
spring:
  application:
    name: meeting-service
  datasource:
    username: <your_username>
    password: <your_password>
    url: <your_database_url>
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
jwt:
  secret: <your_secret>
  expiration: 86400
# AWS IAM CREDS
access:
  key:
    id: <your_access_key>
secret:
  access:
    key: <your_secret_access_key>
app:
  instance:
    arn: <your_app_instance_arn>
# CHIME ACCOUNT
chime:
  account:
    id: <your_chime_account_id>
aws:
  account:
    id: <your_aws_account_id>
# AWS V4 REQUEST SETTINGS
service:
    name: chime
    region: us-east-1
    host: http://node001.ue1.ws-messaging.chime.aws
    endpoint: http://node001.ue1.ws-messaging.chime.aws/connect