server:
  port: 9002
spring:
  application:
    name: contact-service
  datasource:
    username: <your_username>
    password: <your_password>
    url: <your_database_url>
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  secret: <your_secret>
  expiration: 86400
amazonProperties:
  endpointUrl: https://s3.eu-west-3.amazonaws.com
  accessKey: <your_access_key>
  secretKey: <your_secret_key>
  bucketName: <your_bucket_name>
  region: eu-west-3
  linkAvailabilityTime: 252000
  maxSizeForFile: 5767168
